void setup(void);

void loop(void);
void parser(String cmd);
String* arrFrom(byte from, String in[]);
void errorOut();
void output(String msg);
void outputln(String msg);
void btn_a_ISR();
void next(int steps);
void previous(int steps);
void checkSerial();
void sysReset();
void setTime(String parameters[]);
void printTime();
void addApp(byte appID, String parameters[]);
void delApp(int n);
String getApp(int n);
String getApps();
void setApp(int n, String parameters[]);
void swapApps(int a, int b);